#SPDX-License-Identifier: MIT-0
---
X86_DesktopLaunchers:
  - "firefox"
  - "brave-browser"
  - "obsidian"
  - "burp-suite"
  - "caido"
  - "Android-Studio"
  - "Autopsy"
  - "JADX-GUI"
  - "Ghidra"
  - "ByteCode-Viewer"

ARM_DesktopLaunchers:
  - "firefox"
  - "brave-browser"
  - "obsidian"
  - "burp-suite"
  - "caido"
  - "Android-Studio"
  - "JADX-GUI"
  - "Ghidra"
  - "ByteCode-Viewer"

X86_AppPaths:
  - "/usr/bin/firefox"
  - "/usr/bin/brave-browser"
  - "/usr/local/bin/obsidian"
  - "/usr/bin/burpsuite"
  - "/usr/local/bin/caido"
  - "/opt/android-studio/bin/studio"
  - "{{ ansible_facts['env']['HOME'] }}/.local/bin/autopsy"
  - "/opt/jadx/bin/jadx-gui"
  - "{{ ansible_facts['env']['HOME'] }}/.local/bin/ghidra"
  - "{{ ansible_facts['env']['HOME'] }}/.local/bin/bytecode-viewer"

ARM_AppPaths:
  - "/usr/bin/firefox"
  - "/usr/bin/brave-browser"
  - "/usr/local/bin/obsidian"
  - "/usr/bin/burpsuite"
  - "/usr/local/bin/caido"
  - "/opt/android-studio/bin/studio.sh"
  - "/opt/jadx/bin/jadx-gui"
  - "{{ ansible_facts['env']['HOME'] }}/.local/bin/ghidra"
  - "{{ ansible_facts['env']['HOME'] }}/.local/bin/bytecode-viewer"

X86_IconPaths:
  - "/opt/flatpak-icons/apps/scalable/firefox.svg"
  - "/opt/flatpak-icons/apps/scalable/brave-browser.svg"
  - "/opt/flatpak-icons/apps/scalable/obsidian-icon.svg"
  - "/opt/flatpak-icons/apps/scalable/burp.svg"
  - "/opt/flatpak-icons/apps/scalable/caido.png"
  - "/opt/flatpak-icons/apps/scalable/android-studio.svg"
  - "/opt/flatpak-icons/apps/scalable/autopsy.svg"
  - "/opt/flatpak-icons/apps/scalable/jadx.svg"
  - "/opt/flatpak-icons/apps/scalable/ghidra.svg"
  - "/opt/flatpak-icons/apps/scalable/bytecode-viewer.svg"

ARM_IconPaths:
  - "/opt/flatpak-icons/apps/scalable/firefox.svg"
  - "/opt/flatpak-icons/apps/scalable/brave-browser.svg"
  - "/opt/flatpak-icons/apps/scalable/obsidian-icon.svg"
  - "/opt/flatpak-icons/apps/scalable/burp.svg"
  - "/opt/flatpak-icons/apps/scalable/caido.png"
  - "/opt/flatpak-icons/apps/scalable/android-studio.svg"
  - "/opt/flatpak-icons/apps/scalable/jadx.svg"
  - "/opt/flatpak-icons/apps/scalable/ghidra.svg"
  - "/opt/flatpak-icons/apps/scalable/bytecode-viewer.svg"

X86_Comments:
  - "Firefox Web Browser"
  - "Brave Browser"
  - "Obsidian Note Taking App"
  - "Burp Suite Web Proxy & Intruder"
  - "Caido Web Proxy & Intruder"
  - "Android Studio IDE"
  - "Autopsy Forensic Browser"
  - "JADX Decompiler"
  - "Ghidra Decompiler"
  - "ByteCode Viewer Decompiler"

ARM_Comments:
  - "Firefox Web Browser"
  - "Brave Browser"
  - "Obsidian Note Taking App"
  - "Burp Suite Web Proxy & Intruder"
  - "Caido Web Proxy & Intruder"
  - "Android Studio IDE"
  - "JADX Decompiler"
  - "Ghidra Decompiler"
  - "ByteCode Viewer Decompiler"
