#SPDX-License-Identifier: MIT-0
---
- include_tasks: "genymotion.yml"
  when: ansible_facts['architecture'] == "x86_64"

- include_tasks: "waydroid.yml"
  when: ansible_facts['architecture'] == "aarch64"
