---
- name: "Check of the presence of /opt/flatpak-icons"
  stat:
    path: "/opt/flatpak-icons"
  register: flat_remix
  changed_when: false

- name: "Git Cloning https://github.com/perumal-j/flatpak-icons.git"
  git:
    repo: "https://github.com/perumal-j/flatpak-icons.git"
    dest: "/opt/flatpak-icons"
  become: true
  become_method: "sudo"
  when: not flat_remix.stat.exists

- name: "Modifying flat-remix Directory Owner"
  file:
    path: "/opt/flatpak-icons"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    state: directory
    recurse: true
  become: true
  become_method: sudo
  changed_when: false

- name: "Ensure applications directory exists"
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/applications"
    state: directory
    mode: '0755'
  when: ansible_facts['architecture'] == 'x86_64' or ansible_facts['architecture'] == 'aarch64'

- name: "Creating Desktop Launchers for x86_64 and Ubuntu"
  template:
    src: "launchers_x86.j2"
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/{{ item.0 }}.desktop"
    mode: '0644'
  loop: "{{  X86_DesktopLaunchers | zip(X86_AppPaths, X86_IconPaths, X86_Comments) }}"
  vars:
    X86_DesktopLauncher: "{{ item.0 }}"
    X86_AppPath: "{{ item.1 }}"
    X86_IconPath: "{{ item.2 }}"
    X86_Comment: "{{ item.3 }}"
  when: ansible_facts['architecture'] == 'x86_64' and ansible_facts['distribution']|lower == 'ubuntu'

- name: "Creating Desktop Launchers for aarch64 and Ubuntu"
  template:
    src: "launchers_aarch64.j2"
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/{{ item.0 }}.desktop"
    mode: '0644'
  loop: "{{  ARM_DesktopLaunchers | zip(ARM_AppPaths, ARM_IconPaths, ARM_Comments) }}"
  vars:
    ARM_DesktopLauncher: "{{ item.0 }}"
    ARM_AppPath: "{{ item.1 }}"
    ARM_IconPath: "{{ item.2 }}"
    ARM_Comment: "{{ item.3 }}"
  when: ansible_facts['architecture'] == 'aarch64' and ansible_facts['distribution']|lower == 'ubuntu'

- name: "Update desktop database"
  command: update-desktop-database "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/"
  when: ansible_facts['architecture'] == 'x86_64' or ansible_facts['architecture'] == 'aarch64'
  changed_when: false
